name: WhipClaim
version: 1.0
description: A modern advanced user oriented claiming system
author: Chasewhip
depend: [CrashPayment]
softdepend: [Vault]
main: net.crashcraft.whipclaim.WhipClaim
api-version: 1.16