name: ${project.name}
version: ${project.version}
description: A modern advanced user oriented claiming system
author: Chasewhip
depend: [ProtocolLib]
softdepend: [CrashPayment, Vault, GriefPrevention, WorldGuard, PlaceholderAPI, Multiverse-Core, Hyperverse]
main: net.crashcraft.crashclaim.CrashClaim
api-version: 1.16